### ISSUE TITLE
Add authentication using JWT on API

### ISSUE THREAD

**Issue by alexandresaura** [Codeminer42/Punchclock#102]
- Um endpoint que recebe login+senha e devolvem um token JWT no body no formato `{ access_token: "token" }`
  - O token JWT precisa ter: id do usuário (sub) + timestamp pra expirar (exp) + id do token (jti) + assinatura HMAC (HMAC 256 https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/HMAC.html) a chave do HMAC deve ser guardada como envvar assim como já é a chave de OTP
- Um endpoint que recebe um token não expirado e devolve um token com expiraçnao renovada.
  - o token recebido deve ser invalidado. Podemos fazer isso usando o cache do rails, simplesmente guardando o valor true na chave `jwt_jti_denied/#{jti}` com a expiração idêntica ao exp do token a ser invalidado
- A autenticação da API precisa ler o JWT, extrair id do user (sub), timestamp e expiração (exp), e validar se a assinatura bate e o timestamp ainda é válido e se o jti não está na no cache `jwt_jti_denied/#{jti}` como true . Então libera o recurso pra o id solicitado.
  
 Notas: 
 - A gem JWT pode cuidar do formato e algoritmo de assinatura, exemplos: https://github.com/jwt/ruby-jwt#hmac 
 - Mais informações: https://medium.com/tableless/entendendo-tokens-jwt-json-web-token-413c6d1397f6

**Comment by mateuscelio** [comment]
Can I take this onte?

**Comment by hpinheiro-godaddy** [comment]
https://github.com/Codeminer42/Punchclock/pull/134
