### ISSUE TITLE
Github contributions worker should not retry

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#13]
When the Github contributions worker fails it shouldn't retry because GH has limits on its API.

**Comment by wenderjean** [comment]
We may need to use native Sidekiq workers here.

**Comment by geeksilva97** [comment]
I would like to work on it. Can you assign me?

**Comment by geeksilva97** [comment]
I think that it was solved by removing the `Reload Contributions` so the `ReloadGithubContributions` job is not needed anymore. In the future, we can use `sidekiq_options` to configure the `retry` policy.

https://github.com/mperham/sidekiq/wiki/Active-Job#customizing-error-handling
