### ISSUE TITLE
Improvements for "Contributions" page

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#157]
We have a couple of improvements we'd like to add to the Contributions page:

1. User column, use only the user's first and last name
2. Format creation date using "dd/mm/yyyy"
3. In the reviewer column we should use only the first letter of the first and last name (instead of Wender Freese we should present only WF)
4. Format review date using "dd/mm/yyyy"
5. Remove the default auto-complete behavior from the filters (it overrides the date picker)

[PLUS][BUG]

1. There is a bug during the txt exporting process, it doesn't collect only selected rows, we should fix this

**Comment by vinas-go** [comment]
Let get this one!
