### ISSUE TITLE
Rename references of "Padrinho" to "Mentor" in Users feature

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#191]
We want to rename all references of the word "Padrinho" to "Mentor" in the user's domain.

**Comment by wenderjean** [comment]
Hey @CatherineNjenga, initially we want to follow a very simplistic approach by renaming the translation [here](https://github.com/Codeminer42/Punchclock/blob/99a41c1fbf07adaa291b18aab1c8770c43971541/config/locales/pt-BR/models.yml#L174).

**Comment by carloslopes** [comment]
Also, it would be good to show this info on the Allocation Chart in a column between the developer and client names.
