### ISSUE TITLE
Add the client project information to be able to contact them

### ISSUE THREAD

**Issue by fabiosammy** [Codeminer42/Punchclock#218]
For the user to be able to get in touch with a project, sometimes the admin user needs to call, or sent an e-mail to the "client".

To achieve this, create contact information for each project, and more than one.
The data is sensible, so, encrypt the data at the database level.

**Comment by carloslopes** [comment]
I spoke with @wenderjean yesterday and since we already have the CRM with this info, there's no reason to add it here.
