### ISSUE TITLE
Reject reason for contribution

### ISSUE THREAD

**Issue by fabiosammy** [Codeminer42/Punchclock#245]
On the admin side, on the contributions, when the user will reject a contribution, add a select option to select one reason:
* Allocated in the project
* Project is not on the curated list
* No sufficient effort
* PR Abandoned
* Other reason

You can just use a simple "enum" field for this. The default option will be "Other reason"

The "Other reason" will NOT have an option to add some kind of description.

**Comment by tonyaraujop** [comment]
Can i get this one?
