### ISSUE TITLE
Create pages for vacations in the punch normal user side

### ISSUE THREAD

**Issue by fabiosammy** [Codeminer42/Punchclock#275]
For a "normal" user, create pages to see, request or cancel a vacation.

The user should be able to see all your own vacations requests
The normal user cannot cancel a not pending vacation

The form will have only the start date and end date.
The end date cannot be before the start date.
The start and the end date cannot be in the past.
The end date cannot be on the same day as the start date

**Comment by HeitorMC** [comment]
Hello There!

I would like to be assigned to this issue
