### ISSUE TITLE
Codebase contains hardcoded non translated messages

### ISSUE THREAD

**Issue by ramos-ph** [Codeminer42/Punchclock#32]
On the `app/controllers/application_controller.rb` file, there are a few strings that are hardcoded:

![image](https://user-images.githubusercontent.com/50644753/134343473-5da8f155-3166-40ba-b504-e19aa2a40fd6.png)
![image](https://user-images.githubusercontent.com/50644753/134343922-88a964e8-6341-42aa-b610-ee94b7e26657.png)

Most of the strings used calls a translate function, should those cases be the same?

**Comment by adbatista** [comment]
yes we should add I18n and move these texts to a translation file
