### ISSUE TITLE
Add tracking tab in the contribuitions admin page

### ISSUE THREAD

**Issue by fabiosammy** [Codeminer42/Punchclock#404]
To be able to track the users' contributions with some information, add a new tab in the contributions admin page with a "tracking" option.

The tracking is a new boolean field. The default will be false.

Also, add new fields called "notes" and "pending", and both can be null.
The "notes" field is a text field, and should be shown only in the tracking tab on the list, and on every new/show/edit page.
The "pending" is a combobox field, an enum with options "dev", "maintainer" and "other". Also should be shown only in the tracking tab, and in every listed above page.

**Comment by adbatista** [comment]
the access permision: user with role opensource
