### ISSUE TITLE
Redesign Open Source page adding "highlight/recomendado" tag

### ISSUE THREAD

**Issue by joaoGabriel55** [Codeminer42/Punchclock#467]
I think that would be good provide a new design to Open Source page and showing "highlight/recomendado" tag

- Depends of issue #463

![image](https://github.com/Codeminer42/Punchclock/assets/23138717/6a39bdc1-8ea2-4229-a204-8ddd059f628a)

[Figma link](https://www.figma.com/file/czN2pN2w733E1fEckB2niW/Untitled?type=design&node-id=0%3A1&mode=design&t=lA3MbgF2XpHBNFQ9-1)

### Requirements

- To retrieve Issue, PR and Star numbers we can use Github API to show these infos
   https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

**Comment by mwilding-godaddy** [comment]
![253591335-6a39bdc1-8ea2-4229-a204-8ddd059f628a](https://github.com/Codeminer42/Punchclock/assets/125277981/d4b8bea1-892e-494a-b7bf-91e7f6cf8039)

What do you think of moving the "Recomendado" tag to bellow the forks and stars?

**Comment by adbatista** [comment]
nice, I'll add the tag hold, because I'm looking maybe to change the theme
