### ISSUE TITLE
Intermittent test in `spec/features/repositories_spec.rb`

### ISSUE THREAD

**Issue by danielmbrasil** [Codeminer42/Punchclock#482]
Intermittent spec:
https://github.com/Codeminer42/Punchclock/blob/30fb5f535ec670d93f4bb95918a8791a34dec711/spec/features/repositories_spec.rb#L28-L31

Apparently, it only fails when the repositories factory creates a repository with the following programming language: `TMG, compiler-compiler` (returned by `Faker::ProgrammingLanguage.name`).

For more details see https://github.com/Codeminer42/Punchclock/actions/runs/5600698251/jobs/10243481800?pr=474.

**Comment by adbatista** [comment]
solved in https://github.com/Codeminer42/Punchclock/pull/479
