### ISSUE TITLE
Disabled day in Calendar.

### ISSUE THREAD

**Issue by thiagofportella** [Codeminer42/Punchclock#527]
Notice that July 31st should be enabled:

<img width="1115" alt="Captura de Tela 2023-08-24 às 11 54 15" src="https://github.com/Codeminer42/Punchclock/assets/52546576/8b255b04-c6a4-4188-9bf8-af2bd4267619">

<img width="1109" alt="Captura de Tela 2023-08-24 às 11 51 01" src="https://github.com/Codeminer42/Punchclock/assets/52546576/14b4c497-b6fb-4883-8fd3-d24ec8012cd3">

Apparently, this does not happen in development environment.

**Comment by adbatista** [comment]
fixed https://github.com/Codeminer42/Punchclock/pull/514
