### ISSUE TITLE
[Proposal] New login screen

### ISSUE THREAD

**Issue by lukzgois** [Codeminer42/Punchclock#53]
Hi guys, here are some design proposal for the login screen! I've designed two separated screens for login and the 2 step auth, based in https://github.com/Codeminer42/Punchclock/issues/12.

If you guys agree, we can create separated issues for this screens. I'm designing the screens using figma and components, so, I can share the figma file with the components I've created for this screens (form label, form input, button, checkbox, and logo, all of them with different states). Also, I can add more details in the issues, about the spacing, fonts and sizes.

Let me know what you guys think 😄 

---

### Login screen

![Login-final](https://user-images.githubusercontent.com/231633/137413477-377e195a-dc3c-4953-be7a-2348562d4591.png)

### Login screen with errors
![Login with error](https://user-images.githubusercontent.com/231633/137413484-09caa5fc-54a7-4ac1-87ba-323f90439a03.png)

### 2 step code screen
![2 factor](https://user-images.githubusercontent.com/231633/137413489-1fcaaf74-c499-4ed8-8a5e-1783abe3392e.png)

### 2 step code screen with errors
![2 factor with error](https://user-images.githubusercontent.com/231633/137413498-0440f6dd-4dee-42b8-b556-10e67e56da02.png)

**Comment by adbatista** [comment]
great, I'll split this into issues
