### ISSUE TITLE
Bug: Activating and deactivating projects in new_admin not working

### ISSUE THREAD

**Issue by nehamamandelbaum** [Codeminer42/Punchclock#554]
When you edit a project, and try to activate it, or deactivate it, it changes correctly in the database, but the icon in the view used to show if a project is active is not changing correctly: 

How to replicate this bug: 

Go to new_admin/projects, pick a project to edit. 

Try deactivating/activating it, then save the changes. 

Go to the index page, or the show page of that project, check if the icon changed (it didn't).

Check in the rails console to see if the active attribute changed (it did).

**Comment by LucasHFS** [comment]
Working on it.
