### ISSUE TITLE
allow user to reset their own 2fa using recovery codes

### ISSUE THREAD

**Issue by adbatista** [Codeminer42/Punchclock#56]

**Comment by marmitoTH** [comment]
I didn't get what is the bug here, can you elaborate more?

**Comment by adbatista** [comment]
enable 2fa, lose your phone, try to login with recovery code

**Comment by wenderjean** [comment]
@marmitoTH The PR you linked to this issue really solves it? I'm looking at the screenshots and they don't suggest we could use recovery codes. :thinking: 
cc/ @adbatista

**Comment by marmitoTH** [comment]
@wenderjean It does, the recovery code is consumed here [https://github.com/Codeminer42/Punchclock/pull/65/files#diff-81d9818a169a9c805031eebe62f6bf477e0ca272f388ac8991453294bc9cc2faR34](url)

Should I make this explicit on the form? Maybe a text in the footer stating that you can also use the recovery code?

**Comment by wenderjean** [comment]
It'll very useful @marmitoTH, we can create a small text below the input to tell the user they can also use recovery codes.
