### ISSUE TITLE
Generate a random password when creating a new user

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#6]
In the admin dashboard, when creating a new user, the current behavior allows the admin to create a password, sending it to the right after, we should instead generate a random password in our backend and send it to the user by e-mail.

The endpoint is `/admin/users/new`

![image](https://user-images.githubusercontent.com/941776/131348356-ad12dbc6-1dc4-4c92-8bdf-744250180a6c.png)

**Comment by marmitoTH** [comment]
@wenderjean  I'm working on it, but there's something I didn't understand. `[...] and send it to the user by e-mail.` it seems to be the current behavior already, isn't it? After successfully create the user, `notify_user_registration` is being called, and it already sent the user email and password on its body.

**Comment by adbatista** [comment]
We decided to go in another way so this PR will not be necessary anymore thanks for your contribution :D
