### ISSUE TITLE
New Login Screen

### ISSUE THREAD

**Issue by lukzgois** [Codeminer42/Punchclock#61]
Implement a new design for the login screen. I'm attaching the figma file to this issue, so anyone can open it and inspect the sizes, colors and etc. I'm trying to use components to organize the screens, making them more dynamic. As a suggestion, we can try to create the new screens more component-oriented, allowing us to easily customize them in the future.

---

## Login screen
![Login-final](https://user-images.githubusercontent.com/231633/140415318-066b63d5-2076-461f-a336-34f034e660b6.png)

## Login screen with errors
![Login with error](https://user-images.githubusercontent.com/231633/140415350-6f56642e-01f7-408c-8fa5-1b87146fbd70.png)

## Spacing information
![login-spacings](https://user-images.githubusercontent.com/231633/140415299-70deea9e-e53b-4ba5-b080-d36a63ad0678.png)

---

# Grid

The screens were created using a 1280 canvas width, divided into 12 columns, with a 30px margin between them. You can trigger the grid on/off in figma.

![image](https://user-images.githubusercontent.com/231633/140417898-cc3a336b-f835-4d01-82ea-6143732989e3.png)

# Fonts

**Font**: Lato (https://fonts.google.com/specimen/Lato)

# Components

## Heading 1
**Text size**: 32px
**Color**: #161616

## Form Input
**Text label size**: 16px
**Text label color**: #313131
**Input height**: 32px
**Input border**: 1px solid #C4C4C4
**Input background**: #F5F5F5

## Checkbox
**Size**: 20px X 20px
**Background color**: #F5F5F5

## Link
**Color**: #5285D4
**Size**: 12px

## Button
**Height**: 40px
**Text size**: 16px
**Background color**: #C51414

## Copyright information
**Text size**: 12px
**Text color**: #767676
**Line color**: #D6D6D6

# Figma File
[Punchclock.zip](https://github.com/Codeminer42/Punchclock/files/7478410/Punchclock.zip)

**Comment by lukzgois** [comment]
## Punchclock logo

![Logo](https://user-images.githubusercontent.com/231633/140418906-d69ed053-f210-42e0-95b7-866d1bb5620f.png)

**Comment by lukzgois** [comment]
## Sidebar background

![Sidebar-logo](https://user-images.githubusercontent.com/231633/140419166-0a1a07b2-77d1-46be-b2ed-c1da20b12c86.png)

**Comment by lukzgois** [comment]
Feel free to ping me if you need some resources in a larger/smaller scale

**Comment by JonasTeixeira42** [comment]
Can I take and try to solve this one?

**Comment by JonasTeixeira42** [comment]
Can I take and try to solve this one?

**Comment by adbatista** [comment]
go for it
