### ISSUE TITLE
Ruby and rails versions are divergent.

### ISSUE THREAD

**Issue by vinas-go** [Codeminer42/Punchclock#63]
Ruby and rails versions are divergent in Gemfile, tool-versions and README files.

**Comment by wenderjean** [comment]
It would be good to address those changes.

**Comment by vinas-go** [comment]
Gemfile
  - Ruby 2.7.4
  - Rails 6.0.4

.tool-versions
  - Ruby 2.7.2

README
  - Ruby 2.7.1
  - Rails 6.0.3
