### ISSUE TITLE
Modify user creation form and Welcome message

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#7]
In order to better handle the onboard process and make it more secure, we want to get rid of the password field when creating a new user and let them change it in the first access by using the "Forgot my password" flow.

- [x] Make sure that "Forgot my password" is working properly
- [x] Remove password field from the user form
- [x] Modify the "welcome" message and ask the user to modify their password using the "Forgot my password" flow

**Comment by efgalvao** [comment]
I would like to work on this one.

**Comment by efgalvao** [comment]
Hello, I have a question, should I redirect to the user edit Password in the first access and let the possibility of him not editing it by clicking cancel ? Or should I obligate him ?
I'm already creating a random password for the access.

**Comment by adbatista** [comment]
the system should enforce the user to set a password, there's no need for random password
