### ISSUE TITLE
Create UX design system using Tailwind

### ISSUE THREAD

**Issue by wenderjean** [Codeminer42/Punchclock#71]
We decided to modernize our application using new tools and approaches for UI/UX, for that reason we want to create a new design system using [tailwindcss](https://tailwindcss.com/). The main idea here is to perform the setup for Tailwind and also create a minimal set of components to be used for the subsequent redesign tickets.

Suggestion:

- https://bradfrost.com/blog/post/atomic-web-design/

Related ticket:

- https://github.com/Codeminer42/Punchclock/issues/61

**Comment by tauantcamargo** [comment]
let me get this one 😄

**Comment by lukzgois** [comment]
That's interesting 😄 . I'm creating the new screens using a component-driven design approach, so, the components are already separated in the Figma file (I've attached it in the ticket #61). I think you can take a look on it @tauantcamargo, maybe starting to create the components for the new screens.

@wenderjean @adbatista I can create some tickets for each of these new components. What do you think about it?

**Comment by adbatista** [comment]
> @adbatista I can create some tickets for each of these new components. What do you think about it?

that will help, thanks
