### ISSUE TITLE
Delta calculation

### ISSUE THREAD

**Issue by LucasCarrias** [Codeminer42/Punchclock#94]
## What?

Missing validation on time inputs and delta calculation

## How to reproduce

* Access "Multiple Punches"
* Select some project and a day in the calendar
* Insert some duplicated time as bellow:
![image](https://user-images.githubusercontent.com/24925816/158610726-bba87ccb-2cfa-49cf-85f8-955b7cc14b83.png)

## Issues

* A punch is created with the duplicated times:
![image](https://user-images.githubusercontent.com/24925816/158610985-658ef9fc-0c1d-4b40-ba80-3f7227b00c33.png)
* The punch is visible for that day in the homepage, but with the duplicated delta:
![image](https://user-images.githubusercontent.com/24925816/158611315-6f9fa860-11fd-4120-8922-2fc3a9563a2b.png)
* You aren't able to see/fix the duplicated time at the edit page

**Comment by joaoGabriel55** [comment]
Hello @LucasCarrias, I can provide some solution

**Comment by joaoGabriel55** [comment]
I simulated these steps and I could edit one of the duplicated times that I registered. I think that it would be good to provide validation when the user tries to register, at multiple punches, some duplicated time. What do you think?
